### ISSUE TITLE
Deprecation warning in Ansible 2.2

### ISSUE THREAD

**Issue by mongrelion** [dochang/ansible-role-pip#1]
Hi!

Thanks for creating this role. I have been using it for a while and it works like a charm.
I recently upgraded my Ansible version and have since then seen a deprecation warning regarding your role `dochang/pip`. Here's the output of the deprecation message:

```
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting  deprecation_warnings=False in ansible.cfg.
```

Any chances of getting this fixed? Not that it's a pressing issue but after 2.4 this might make the role unusable.

**Comment by dochang** [comment]
Thanks for your reminder.

`check_mode` is introduced in Ansible 2.2.  Ansible 2.1 doesn't know about it.  For backward compatibility, I can't simply add `check_mode: no`.

To solve this problem, I will release version 1.0, which still uses `always_run`.  This version supports Ansible 1.9.x to 2.3.x.

When Ansible 2.4 is released, I will release version 2.0, which uses `check_mode`.  This version supports Ansible 2.2 and up.

What do you think about this solution?  Comments are welcome.

**Comment by mongrelion** [comment]
Sounds good to me, although what's stopping you from releasing both version 1.0 with `always_run` and version 2.0 with `check_mode` at the same time, right? or you think that's gonna be an issue for newcomers?

**Comment by dochang** [comment]
Let's think again.

The reason we use `always_run` is to test whether `pip` exists in check mode.  But it makes no sense to do this test, because we won't download and install pip in check mode at all.  We can simply skip both the test and the `install.yml` playbook.  So just remove `always_run`, no `check_mode`.

Please try the `next` branch.  I think it will keep the backward compatibility.

**Comment by mongrelion** [comment]
It works!
